language: java

jdk:
  - oraclejdk8
  - oraclejdk7

after_success: gradle javadoc sonarRunner

deploy:
  provider: releases
  file: "build"
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
