language: java
jdk:
- oraclejdk8
- oraclejdk7

after_success: gradle javadoc sonarRunner

deploy:
  provider: releases
  api-key: "a26d9d2692e5267d7227c2675859ab06c213fda0"
  file: build
  skip_cleanup: true
  on:
    tags: true
    all_branches: true


notifications:
  email: true
