language: java
jdk:
- oraclejdk8
- oraclejdk7

after_success: gradle javadoc sonarRunner

deploy:
  provider: releases
  user: "theofidry"
  password:
      secure: ixbMI64lmFfAet7JdiBIOK5XdXb/W49owPVbvuUOUJcuAXWw6+OneuKMwN2VRCv3sUG3D8yPZJ2cXiyYaqDCqhjZKvcyu95CMQ8a4udomi+BOtXMQJQ7uZpb3VFE+7+d5F/gk227U1i1fVxpcILXYQI+8ra9gUEyEOM7YgSRZdM=
  file: build
  skip_cleanup: true
  on:
    tags: true
    all_branches: true


notifications:
  email: true
